# Generated by Django 5.0.4 on 2024-05-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selvina_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=1000)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="URLConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=150, null=True)),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                ("about_us", models.TextField(blank=True, null=True)),
                (
                    "about_us_img",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "URLConfiguration",
            },
        ),
    ]
