# Generated by Django 5.0.4 on 2024-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selvina_app", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="digital",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
