# Generated by Django 5.0.4 on 2024-05-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selvina_app", "0006_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
